### ISSUE TITLE
Flaky scanner test panics

### ISSUE THREAD

**Issue by gz-c** [skycoin/teller#211]
https://travis-ci.org/skycoin/teller/builds/339379493

```
panic: send on closed channel

goroutine 24 [running]:
github.com/skycoin/teller/src/scanner.(*BaseScanner).processDeposit(0xc42025c5a0, 0x87e3a4, 0x3, 0xc4211303c0, 0x22, 0x2eebb80, 0x396c6, 0xc420d21180, 0x40, 0x0, ...)
	github.com/skycoin/teller/src/scanner/_test/_obj_test/base_scanner.go:119 +0x363
github.com/skycoin/teller/src/scanner.(*BaseScanner).Run.func3(0xc4210f12d0, 0xc4202300a0, 0xc42025c5a0)
	github.com/skycoin/teller/src/scanner/_test/_obj_test/base_scanner.go:364 +0x287
created by github.com/skycoin/teller/src/scanner.(*BaseScanner).Run
	github.com/skycoin/teller/src/scanner/_test/_obj_test/base_scanner.go:352 +0x82c
FAIL	github.com/skycoin/teller/src/scanner	6.841s
make: *** [test] Error 1
```

**Comment by stgleb** [comment]
Cannot reproduce, looks like tests are fixed on CI

**Comment by gz-c** [comment]
That's why its flaky, only happens rarely

**Comment by therealssj** [comment]
https://github.com/skycoin/teller/pull/229
fixed in this?

**Comment by gz-c** [comment]
not sure. if it was related to the race condition with the logger, then possibly.  the other race conditions were in the tests themselves
